### ISSUE TITLE
Containers that exceed the limit time are automatically deleted

### ISSUE THREAD

**Issue by Sestunnwed** [touero/easier-docker#23]
When I start a container, if I find that its time exceeds the limit, I will delete it and run a new container. Is this possible?

**Comment by Sestunnwed** [comment]
@touero No need to delete dynamically

**Comment by touero** [comment]
Of course, it seems that this can only be done when the container is
started. If your program is not running in a container, the container is
just a service. This may be done in your program.

Sestunnwed ***@***.***> 于2024年11月26日周二 10:17写道：

**Comment by Sestunnwed** [comment]
@touero , Thank, I will try

**Comment by touero** [comment]
On Tue, Nov 26, 2024 at 11:38 AM Sestunnwed ***@***.***>
wrote:

> @touero <https://github.com/touero> , Thank, I will try
>

Looking forward to your pr
```
   touero
```

**Comment by Sestunnwed** [comment]
I'm not that familiar please let @Esic25 try it out.

**Comment by touero** [comment]
On Tue, Nov 26, 2024 at 12:02 PM Sestunnwed wrote:

> I'm not that familiar please let @Esic25 <https://github.com/Esic25> try
> it out.
>
>
> Message ID: ***@***.***>
>
I don't know his situation.

        touero

**Comment by touero** [comment]
#26

**Comment by touero** [comment]
In version 2.2.6 it is finished.
